adw:
    resource: "@AdwBundle/Resources/config/routing.yml"
    prefix:   /

home:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

preview:
    path:      /preview
    defaults:  { _controller: AppBundle:Default:preview }
